window.addEventListener("load",()=>setTimeout(()=>document.getElementById("splash")?.classList.add("hide"),700));
const firebaseConfig={apiKey:"AIzaSyCSVjnXaDyOQnqNx6HXjwYNqrJu96v8V_U",authDomain:"family-recipes-by-melissa.firebaseapp.com",databaseURL:"https://family-recipes-by-melissa-default-rtdb.firebaseio.com",projectId:"family-recipes-by-melissa",storageBucket:"family-recipes-by-melissa.firebasestorage.app",messagingSenderId:"644873856163",appId:"1:644873856163:web:1b184c62882c7ae0ff8b16",measurementId:"G-CJZ66HXCZN"};
const categories=window.MELISSA_RECIPE_CATEGORIES||[];
const builtInRecipes=(window.MELISSA_BUILT_IN_RECIPES||[]).map(normalizeRecipe);
const LOCAL_KEY="melissasRecipeBinderBackupV2";
const defaultState={recipes:builtInRecipes,mealPlan:"",freezer:[],shopping:[],christmas:"Breakfast casserole\nDinner menu\nDesserts\nShopping list",easter:"Brunch menu\nDinner menu\nDesserts",mothersDay:"Brunch ideas\nFamily favorites",thanksgiving:"Turkey day sides\nBreakfast for the weekend\nDesserts",gatherings:"Birthdays, cookouts, family dinners, and potlucks",familyNotes:""};
const $=id=>document.getElementById(id);
let state=structuredClone(defaultState),selectedCategory="",activeRecipeIndex=null,saveTimer=null,db=null,dataRef=null,firebaseReady=false;
function normalizeRecipe(recipe={}){return{category:recipe.category||"Other",title:String(recipe.title||"Untitled Recipe").trim(),ingredients:String(recipe.ingredients||""),directions:String(recipe.directions||""),notes:String(recipe.notes||""),rating:String(recipe.rating||""),photo:""}}
function normalizeRecipeCollection(value){if(Array.isArray(value))return value.filter(Boolean).map(normalizeRecipe);if(value&&typeof value==="object")return Object.values(value).filter(Boolean).map(normalizeRecipe);return[]}
function recipeKey(recipe){return String(recipe.title||"").trim().toLowerCase()}
function mergeRecipes(...collections){const merged=[],seen=new Set();collections.flat().forEach(raw=>{const recipe=normalizeRecipe(raw),key=recipeKey(recipe);if(!key||seen.has(key))return;seen.add(key);merged.push(recipe)});return merged}
function loadLocalState(){try{const saved=JSON.parse(localStorage.getItem(LOCAL_KEY)||"null");if(saved&&typeof saved==="object"){state={...structuredClone(defaultState),...saved};state.recipes=mergeRecipes(normalizeRecipeCollection(saved.recipes),builtInRecipes);state.shopping=Array.isArray(saved.shopping)?saved.shopping:[];state.freezer=Array.isArray(saved.freezer)?saved.freezer:[]}}catch(error){console.warn("Could not read local recipe backup",error)}}
function saveLocal(){try{localStorage.setItem(LOCAL_KEY,JSON.stringify(state))}catch(error){console.warn("Could not save local recipe backup",error)}}
function setStatus(text){$("status").textContent=text}
function saveNow(){saveLocal();setStatus(firebaseReady?"Saving online...":"Saved on this device");clearTimeout(saveTimer);if(!firebaseReady||!dataRef)return;saveTimer=setTimeout(()=>dataRef.set(state).then(()=>setStatus("Saved online and on this device")).catch(error=>{console.error(error);setStatus("Saved on this device — online sync unavailable")}),450)}
function setupFirebase(){try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);db=firebase.database();dataRef=db.ref("melissasRecipeBinder");dataRef.once("value").then(snapshot=>{const remote=snapshot.val()||{},remoteRecipes=normalizeRecipeCollection(remote.recipes),localRecipes=normalizeRecipeCollection(state.recipes);state={...structuredClone(defaultState),...state,...remote};state.recipes=mergeRecipes(remoteRecipes,localRecipes,builtInRecipes);state.shopping=Array.isArray(state.shopping)?state.shopping:[];state.freezer=Array.isArray(state.freezer)?state.freezer:[];firebaseReady=true;saveLocal();renderAll();const remoteKeys=new Set(remoteRecipes.map(recipeKey));const hasMissing=state.recipes.some(recipe=>!remoteKeys.has(recipeKey(recipe)));if(hasMissing||!snapshot.exists())saveNow();else setStatus("Saved online and on this device")}).catch(error=>{console.error(error);firebaseReady=false;setStatus("Using on-device recipes — online sync unavailable");renderAll()})}catch(error){console.error(error);setStatus("Using on-device recipes — Firebase did not load")}}
function optionMarkup(selected){return categories.map(category=>`<option ${category===selected?"selected":""}>${escapeHtml(category)}</option>`).join("")}
function setupCategorySelects(){$("importCategory").innerHTML=optionMarkup("Dinner");$("photoImportCategory").innerHTML=optionMarkup("Family Favorites");$("editCategory").innerHTML=optionMarkup("Dinner")}
function categoryIcon(category){const icons={Breakfast:"🍳",Lunch:"🥪",Dinner:"🍽️",Desserts:"🧁",Appetizers:"🥨","Side Dishes":"🥗","Soups & Stews":"🥣","Crockpot / Slow Cooker":"🍲","Instant Pot":"⏱️","Freezer Meals":"❄️","Holiday Recipes":"🎄","Family Favorites":"💜",Other:"📒"};return icons[category]||"📒"}
function renderCategories(){const counts=new Map(categories.map(category=>[category,0]));state.recipes.forEach(recipe=>counts.set(recipe.category,(counts.get(recipe.category)||0)+1));$("categoryGrid").innerHTML=categories.map(category=>`<button class="category-button" data-category="${escapeHtml(category)}"><span class="category-name">${categoryIcon(category)} ${escapeHtml(category)}</span><span class="category-count">${counts.get(category)||0} recipe${counts.get(category)===1?"":"s"}</span></button>`).join("");document.querySelectorAll(".category-button").forEach(button=>button.onclick=()=>openCategory(button.dataset.category))}
function openCategory(category){selectedCategory=category;$("searchBox").value="";$("clearSearchBtn").classList.add("hidden");$("categoryHome").classList.add("hidden");$("recipeBrowser").classList.remove("hidden");renderRecipeList()}
function showCategories(){selectedCategory="";$("searchBox").value="";$("clearSearchBtn").classList.add("hidden");$("recipeBrowser").classList.add("hidden");$("recipeEditor").classList.add("hidden");$("categoryHome").classList.remove("hidden");renderCategories()}
function searchableText(recipe){return `${recipe.title} ${recipe.ingredients}`.toLowerCase().replace(/[^a-z0-9]+/g," ")}
function searchMatches(recipe,query){const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean),haystack=searchableText(recipe);return terms.every(term=>haystack.includes(term))}
function recipePreview(recipe){const first=(recipe.ingredients||"").split(/\r?\n/).filter(Boolean).slice(0,3).join(" • ");return first||"Open this recipe to view the ingredients and directions."}
function renderRecipeList(){const query=$("searchBox").value.trim();let matches=state.recipes.map((recipe,index)=>({recipe,index}));if(query)matches=matches.filter(item=>searchMatches(item.recipe,query));else if(selectedCategory)matches=matches.filter(item=>item.recipe.category===selectedCategory);else matches=[];$("recipeListHeading").textContent=query?`Search Results (${matches.length})`:`${selectedCategory} (${matches.length})`;if(!matches.length){$("recipeList").innerHTML=`<div class="empty-state">${query?"No recipes match that partial name or ingredient.":"No recipes are saved in this category yet."}</div>`;return}$("recipeList").innerHTML=matches.map(({recipe,index})=>`<article class="recipe-summary"><div class="section-title"><div><h4>${escapeHtml(recipe.title)}</h4><span class="badge">${escapeHtml(recipe.category)}</span></div><div class="actions"><button data-open-index="${index}">Open</button><button class="secondary" data-share-index="${index}">Share PDF</button></div></div><p>${escapeHtml(recipePreview(recipe))}</p></article>`).join("");document.querySelectorAll("[data-open-index]").forEach(button=>button.onclick=()=>openRecipeEditor(Number(button.dataset.openIndex)));document.querySelectorAll("[data-share-index]").forEach(button=>button.onclick=()=>shareRecipePdf(Number(button.dataset.shareIndex)))}
function openRecipeEditor(index,recipeOverride=null){activeRecipeIndex=Number.isInteger(index)?index:null;const recipe=normalizeRecipe(recipeOverride||(activeRecipeIndex===null?{category:selectedCategory||"Dinner",title:"",ingredients:"",directions:"",notes:"",rating:""}:state.recipes[activeRecipeIndex]));$("editorHeading").textContent=activeRecipeIndex===null?"New Recipe":recipe.title;$("editCategory").innerHTML=optionMarkup(recipe.category);$("editTitle").value=recipe.title==="Untitled Recipe"?"":recipe.title;$("editIngredients").value=recipe.ingredients;$("editDirections").value=recipe.directions;$("editNotes").value=recipe.notes;$("editRating").value=recipe.rating;$("deleteRecipeBtn").classList.toggle("hidden",activeRecipeIndex===null);$("recipeEditor").classList.remove("hidden");$("recipeEditor").scrollIntoView({behavior:"smooth",block:"start"})}
function readEditorRecipe(){return normalizeRecipe({category:$("editCategory").value||"Other",title:$("editTitle").value.trim()||"Untitled Recipe",ingredients:$("editIngredients").value.trim(),directions:$("editDirections").value.trim(),notes:$("editNotes").value.trim(),rating:$("editRating").value.trim(),photo:""})}
function saveEditorRecipe(){const recipe=readEditorRecipe();if(activeRecipeIndex===null){state.recipes.unshift(recipe);activeRecipeIndex=0}else state.recipes[activeRecipeIndex]=recipe;selectedCategory=recipe.category;saveNow();renderAll();$("recipeEditor").classList.add("hidden");$("categoryHome").classList.add("hidden");$("recipeBrowser").classList.remove("hidden");renderRecipeList()}
function deleteActiveRecipe(){if(activeRecipeIndex===null)return;const recipe=state.recipes[activeRecipeIndex];if(!confirm(`Delete ${recipe.title}?`))return;state.recipes.splice(activeRecipeIndex,1);activeRecipeIndex=null;$("recipeEditor").classList.add("hidden");saveNow();renderAll()}
function parseRecipeText(text){const lines=String(text||"").replace(/\r/g,"").split("\n").map(line=>line.replace(/\s+/g," ").trim()).filter(Boolean);if(!lines.length)return{title:"Imported Recipe",ingredients:"",directions:"",notes:""};const lower=lines.map(line=>line.toLowerCase()),headingIndex=names=>lower.findIndex(line=>names.some(name=>line===name||line.startsWith(`${name}:`))),ingredientsIndex=headingIndex(["ingredients","ingredient"]),directionsIndex=headingIndex(["directions","instructions","instruction","method","preparation"]),notesIndex=headingIndex(["notes","note","tips","pro tips"]);let title=lines[0].replace(/^(recipe\s*:?\s*)/i,""),ingredients=[],directions=[],notes=[];if(ingredientsIndex>=0&&directionsIndex>ingredientsIndex){ingredients=lines.slice(ingredientsIndex+1,directionsIndex);const end=notesIndex>directionsIndex?notesIndex:lines.length;directions=lines.slice(directionsIndex+1,end);if(notesIndex>directionsIndex)notes=lines.slice(notesIndex+1);if(ingredientsIndex>0)title=lines.slice(0,ingredientsIndex).find(line=>!/^(prep|cook|total|servings?|yield)/i.test(line))||title}else{const instructionStart=lines.findIndex((line,index)=>index>0&&(/^(\d+[.)]|step\s+\d+|preheat|heat |place |add |combine |mix |stir |whisk |bake |cook |pour |serve |cover |remove )/i.test(line)));if(instructionStart>1){ingredients=lines.slice(1,instructionStart);directions=lines.slice(instructionStart)}else{ingredients=lines.slice(1).filter(line=>/^(\d|[¼½¾⅓⅔]|one |two |three )|\b(cup|cups|tsp|teaspoon|tbsp|tablespoon|oz|ounce|lb|pound|clove|can|package|pinch)\b/i.test(line));const ingredientSet=new Set(ingredients);directions=lines.slice(1).filter(line=>!ingredientSet.has(line))}}return{title:title||"Imported Recipe",ingredients:ingredients.join("\n"),directions:directions.join("\n"),notes:notes.join("\n")}}
function reviewPastedRecipe(){const text=$("importText").value.trim();if(!text)return alert("Paste a recipe first.");const parsed=parseRecipeText(text);openRecipeEditor(null,{...parsed,category:$("importCategory").value||"Other",rating:"",photo:""});$("importPanel").classList.add("hidden")}
async function extractRecipeFromPhoto(){const file=$("photoImportFile").files[0];if(!file)return alert("Choose a recipe photo first.");if(!window.Tesseract)return alert("The photo reader did not load. Check your internet connection and try again.");const button=$("extractPhotoBtn");button.disabled=true;$("ocrStatus").textContent="Starting photo reader...";try{const result=await Tesseract.recognize(file,"eng",{logger:message=>{if(message.status==="recognizing text")$("ocrStatus").textContent=`Reading recipe... ${Math.round((message.progress||0)*100)}%`;else if(message.status)$("ocrStatus").textContent=message.status.charAt(0).toUpperCase()+message.status.slice(1)+"..."}}),parsed=parseRecipeText(result.data.text);openRecipeEditor(null,{...parsed,category:$("photoImportCategory").value||"Other",notes:parsed.notes?`${parsed.notes}\nImported from a photo; the photo was not saved.`:"Imported from a photo; the photo was not saved.",rating:"",photo:""});$("photoImportPanel").classList.add("hidden");$("ocrStatus").textContent="Recipe text extracted. Review it before saving."}catch(error){console.error(error);$("ocrStatus").textContent="The photo could not be read. Try a brighter, straighter photo with clear text."}finally{button.disabled=false}}
function pdfSafeFilename(title){return`${String(title||"recipe").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"recipe"}.pdf`}
function createRecipePdf(recipe){if(!window.jspdf?.jsPDF)throw new Error("PDF library unavailable");const{jsPDF}=window.jspdf,doc=new jsPDF({unit:"pt",format:"letter"}),margin=52,pageWidth=doc.internal.pageSize.getWidth(),pageHeight=doc.internal.pageSize.getHeight(),contentWidth=pageWidth-margin*2;let y=58;const ensureSpace=needed=>{if(y+needed>pageHeight-52){doc.addPage();y=58}},writeLines=(text,size=11,bold=false)=>{doc.setFont("helvetica",bold?"bold":"normal");doc.setFontSize(size);const lines=doc.splitTextToSize(String(text||""),contentWidth);lines.forEach(line=>{ensureSpace(size+6);doc.text(line,margin,y);y+=size+5})};doc.setFont("helvetica","bold");doc.setFontSize(20);doc.text(recipe.title,margin,y);y+=27;doc.setFont("helvetica","normal");doc.setFontSize(10);doc.text(recipe.category,margin,y);y+=23;const section=(heading,text)=>{if(!text)return;ensureSpace(35);doc.setFont("helvetica","bold");doc.setFontSize(13);doc.text(heading,margin,y);y+=19;writeLines(text,11,false);y+=11};section("Ingredients",recipe.ingredients);section("Directions",recipe.directions);section("Notes",recipe.notes);section("Family Rating / Comments",recipe.rating);ensureSpace(30);doc.setFont("helvetica","italic");doc.setFontSize(9);doc.text("Shared from Melissa's Recipe Binder",margin,y);return doc}
async function shareRecipePdf(index){const recipe=index===null||index===undefined?readEditorRecipe():state.recipes[index];try{const doc=createRecipePdf(recipe),filename=pdfSafeFilename(recipe.title),blob=doc.output("blob"),file=new File([blob],filename,{type:"application/pdf"});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:recipe.title,text:`Recipe: ${recipe.title}`,files:[file]});else{doc.save(filename);alert("The PDF was downloaded. Attach it to an email or text message from your Downloads folder.")}}catch(error){if(error?.name!=="AbortError"){console.error(error);alert("The PDF could not be created. Please try again.")}}}
function syncTextAreas(){["mealPlan","christmas","easter","mothersDay","thanksgiving","gatherings","familyNotes"].forEach(id=>{if(document.activeElement!==$(id))$(id).value=state[id]||""})}
function renderList(id,items){$(id).innerHTML="";items.forEach((item,index)=>{const li=document.createElement("li");li.className=item.done?"done":"";li.innerHTML=`<input type="checkbox" ${item.done?"checked":""} data-list-toggle="${id}" data-index="${index}"> ${escapeHtml(item.text)} ${item.date?`<span class="small">(${escapeHtml(item.date)})</span>`:""} <button class="danger" data-list-remove="${id}" data-index="${index}">×</button>`;$(id).appendChild(li)});document.querySelectorAll(`[data-list-toggle="${id}"]`).forEach(box=>box.onchange=()=>toggleListItem(id,Number(box.dataset.index)));document.querySelectorAll(`[data-list-remove="${id}"]`).forEach(button=>button.onclick=()=>removeListItem(id,Number(button.dataset.index)))}
function toggleListItem(id,index){const list=id==="shoppingList"?state.shopping:state.freezer;list[index].done=!list[index].done;saveNow();renderAll()}
function removeListItem(id,index){const list=id==="shoppingList"?state.shopping:state.freezer;list.splice(index,1);saveNow();renderAll()}
function renderAll(){renderCategories();syncTextAreas();renderList("shoppingList",state.shopping||[]);renderList("freezerList",state.freezer||[]);if(!$("recipeBrowser").classList.contains("hidden"))renderRecipeList()}
function escapeHtml(value){return String(value||"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]))}
function bindEvents(){document.querySelectorAll("nav button").forEach(button=>button.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(element=>element.classList.remove("active"));button.classList.add("active");$(button.dataset.tab).classList.add("active")});$("addRecipeBtn").onclick=()=>openRecipeEditor(null,{category:selectedCategory||"Dinner",title:"",ingredients:"",directions:"",notes:"",rating:""});$("openImportBtn").onclick=()=>$("importPanel").classList.remove("hidden");$("closeImportBtn").onclick=()=>$("importPanel").classList.add("hidden");$("importRecipeBtn").onclick=reviewPastedRecipe;$("openPhotoImportBtn").onclick=()=>$("photoImportPanel").classList.remove("hidden");$("closePhotoImportBtn").onclick=()=>$("photoImportPanel").classList.add("hidden");$("extractPhotoBtn").onclick=extractRecipeFromPhoto;$("backToCategoriesBtn").onclick=showCategories;$("searchBox").oninput=()=>{const query=$("searchBox").value.trim();$("clearSearchBtn").classList.toggle("hidden",!query);if(query){selectedCategory="";$("categoryHome").classList.add("hidden");$("recipeBrowser").classList.remove("hidden");renderRecipeList()}else showCategories()};$("clearSearchBtn").onclick=showCategories;$("closeEditorBtn").onclick=()=>$("recipeEditor").classList.add("hidden");$("saveRecipeBtn").onclick=saveEditorRecipe;$("deleteRecipeBtn").onclick=deleteActiveRecipe;$("shareRecipeBtn").onclick=()=>shareRecipePdf(null);["mealPlan","christmas","easter","mothersDay","thanksgiving","gatherings","familyNotes"].forEach(id=>$(id).oninput=()=>{state[id]=$(id).value;saveNow()});$("addShoppingBtn").onclick=()=>{const text=$("shoppingItem").value.trim();if(!text)return;state.shopping.push({text,done:false});$("shoppingItem").value="";saveNow();renderAll()};$("addFreezerBtn").onclick=()=>{const text=$("freezerItem").value.trim();if(!text)return;state.freezer.push({text,date:$("freezerDate").value,done:false});$("freezerItem").value="";$("freezerDate").value="";saveNow();renderAll()};$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="melissas-recipe-binder-backup.json";link.click();URL.revokeObjectURL(link.href)};$("resetBtn").onclick=()=>{if(!confirm("Reset the binder to the built-in recipes? This removes recipes and lists you added."))return;state=structuredClone(defaultState);saveNow();showCategories();renderAll()}}
loadLocalState();setupCategorySelects();bindEvents();renderAll();setStatus("Recipes loaded from this device");setupFirebase();if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js?v=20260804-1").then(registration=>registration.update()).catch(console.error);
