window.addEventListener("load",()=>{setTimeout(()=>{const s=document.getElementById("splash");if(s)s.classList.add("hide")},2200)});
const firebaseConfig={apiKey:"AIzaSyCSVjnXaDyOQnqNx6HXjwYNqrJu96v8V_U",authDomain:"family-recipes-by-melissa.firebaseapp.com",databaseURL:"https://family-recipes-by-melissa-default-rtdb.firebaseio.com",projectId:"family-recipes-by-melissa",storageBucket:"family-recipes-by-melissa.firebasestorage.app",messagingSenderId:"644873856163",appId:"1:644873856163:web:1b184c62882c7ae0ff8b16",measurementId:"G-CJZ66HXCZN"};
firebase.initializeApp(firebaseConfig);
const db=firebase.database(),dataRef=db.ref("melissasRecipeBinder");
const categories=["Breakfast","Lunch","Dinner","Desserts","Appetizers","Side Dishes","Soups & Stews","Crockpot / Slow Cooker","Instant Pot","Freezer Meals","Holiday Recipes","Family Favorites","Other"];
const starterRecipes=[{category:"Breakfast",title:"Hash Brown Crust Breakfast Casserole",ingredients:"30 oz thawed hash browns\n3 tbsp melted butter\n1 lb breakfast sausage\n8 oz mushrooms, sliced\n2 cups spinach\n10 eggs\n1 cup milk\n2 cups shredded cheddar cheese\nSalt, pepper, garlic powder, onion powder",directions:"Press hash browns with butter into a greased 9x13 pan. Bake at 425°F for 20-25 minutes. Cook sausage, mushrooms, and spinach. Layer over crust. Whisk eggs, milk, and seasonings. Pour over filling. Top with cheese. Bake at 375°F for 30-35 minutes.",notes:"Freezes well. Cool completely before freezing.",rating:"",photo:""},{category:"Breakfast",title:"Cinnamon Roll Casserole",ingredients:"2 cans cinnamon rolls\n4 eggs\n1/2 cup milk or cream\n1 tsp vanilla\n1 tsp cinnamon",directions:"Cut cinnamon rolls into pieces. Place in greased baking dish. Whisk eggs, milk, vanilla, and cinnamon. Pour over rolls. Bake at 350°F for 25-30 minutes. Add icing after baking.",notes:"Best frozen after baking.",rating:"",photo:""}];
const defaultState={recipes:starterRecipes,mealPlan:"",freezer:[],shopping:[],christmas:"Breakfast casserole\nDinner menu\nDesserts\nShopping list",easter:"Brunch menu\nDinner menu\nDesserts",mothersDay:"Brunch ideas\nFamily favorites",thanksgiving:"Turkey day sides\nBreakfast for the weekend\nDesserts",gatherings:"Birthdays, cookouts, family dinners, and potlucks",familyNotes:""};
const $=id=>document.getElementById(id);let state=structuredClone(defaultState),loaded=false,saveTimer=null;
function saveNow(){if(!loaded)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{dataRef.set(state);$("status").textContent="Saved online"}
function setupCats(){let opts='<option value="All">All Recipes</option>'+categories.map(c=>`<option>${c}</option>`).join("");$("categoryFilter").innerHTML=opts;$("importCategory").innerHTML=categories.map(c=>`<option ${c==="Dinner"?"selected":""}>${c}</option>`).join("");$("scanCategory").innerHTML=categories.map(c=>`<option ${c==="Family Favorites"?"selected":""}>${c}</option>`).join("")}
window.addEventListener("DOMContentLoaded", () => {
  setupCats();
});
dataRef.on("value",snap=>{const data=snap.val();state=data?{...structuredClone(defaultState),...data}:structuredClone(defaultState);if(!data)dataRef.set(defaultState);loaded=true;syncInputs();renderAll();$("status").textContent="Saved online with Firebase"},err=>{$("status").textContent="Firebase connection error";console.error(err)});
document.querySelectorAll("nav button").forEach(btn=>{btn.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active");$(btn.dataset.tab).classList.add("active")}});
function syncInputs(){["mealPlan","christmas","easter","mothersDay","thanksgiving","gatherings","familyNotes"].forEach(id=>{if(document.activeElement!==$(id))$(id).value=state[id]||""})}
["mealPlan","christmas","easter","mothersDay","thanksgiving","gatherings","familyNotes"].forEach(id=>{$(id).oninput=()=>{state[id]=$(id).value;saveNow()}});
$("categoryFilter").onchange=renderRecipes;$("searchBox").oninput=renderRecipes;
$("openImportBtn").onclick=()=>$("importPanel").classList.remove("hidden");$("closeImportBtn").onclick=()=>$("importPanel").classList.add("hidden");$("openScanBtn").onclick=()=>$("scanPanel").classList.remove("hidden");$("closeScanBtn").onclick=()=>$("scanPanel").classList.add("hidden");
$("addRecipeBtn").onclick=()=>{state.recipes.unshift({category:"Dinner",title:"New Recipe",ingredients:"",directions:"",notes:"",rating:"",photo:""});saveNow();renderRecipes()};
$("importRecipeBtn").onclick=()=>{const text=$("importText").value.trim();if(!text)return alert("Paste a recipe first.");const p=parseRecipe(text);state.recipes.unshift({category:$("importCategory").value||"Other",title:p.title||"Imported Recipe",ingredients:p.ingredients,directions:p.directions,notes:p.notes,rating:"",photo:""});$("importText").value="";$("importPanel").classList.add("hidden");saveNow();renderRecipes()};
$("saveScanBtn").onclick=()=>{const file=$("scanPhoto").files[0];const rec={category:$("scanCategory").value||"Family Favorites",title:$("scanTitle").value.trim()||"Scanned Recipe",ingredients:"",directions:"",notes:$("scanNotes").value||"Recipe photo saved. Add ingredients and directions later.",rating:"",photo:""};if(!file){state.recipes.unshift(rec);clearScan();saveNow();renderRecipes();return}resizeImage(file,900,url=>{rec.photo=url;state.recipes.unshift(rec);clearScan();saveNow();renderRecipes()})};
function clearScan(){$("scanTitle").value="";$("scanPhoto").value="";$("scanNotes").value="";$("scanPanel").classList.add("hidden")}
function parseRecipe(text){const lines=text.split(/\r?\n/).map(l=>l.trim()).filter(Boolean),title=lines[0]||"Imported Recipe",low=lines.map(l=>l.toLowerCase());let i=low.findIndex(l=>l.includes("ingredients")),d=low.findIndex(l=>l.includes("directions")||l.includes("instructions")||l.includes("method"));if(i>=0&&d>i)return{title,ingredients:lines.slice(i+1,d).join("\n"),directions:lines.slice(d+1).join("\n"),notes:""};return{title,ingredients:"",directions:"",notes:lines.slice(1).join("\n")}}
function resizeImage(file,maxWidth,cb){const reader=new FileReader();reader.onload=e=>{const img=new Image();img.onload=()=>{const scale=Math.min(maxWidth/img.width,1),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);cb(c.toDataURL("image/jpeg",.72))};img.src=e.target.result};reader.readAsDataURL(file)}
function categoryOptions(sel){return categories.map(c=>`<option ${c===sel?"selected":""}>${c}</option>`).join("")}
function renderRecipes(){$("recipeList").innerHTML="";const filter=$("categoryFilter").value||"All",search=($("searchBox").value||"").toLowerCase().trim();state.recipes.forEach((r,i)=>{const hay=`${r.title} ${r.category} ${r.ingredients} ${r.directions} ${r.notes} ${r.rating}`.toLowerCase();if(filter!=="All"&&r.category!==filter)return;if(search&&!hay.includes(search))return;const div=document.createElement("div");div.className="card";div.innerHTML=`<div class="card-title"><h3>${esc(r.title||"Untitled Recipe")}</h3><span class="badge">${esc(r.category||"Other")}</span></div>${r.photo?`<img src="${r.photo}" class="recipe-photo">`:""}<label>Category</label><select data-i="${i}" data-field="category">${categoryOptions(r.category||"Other")}</select><label>Recipe Name</label><input value="${esc(r.title)}" data-i="${i}" data-field="title"><label>Ingredients</label><textarea data-i="${i}" data-field="ingredients">${esc(r.ingredients)}</textarea><label>Directions</label><textarea data-i="${i}" data-field="directions">${esc(r.directions)}</textarea><label>Notes / Freezer Instructions / Changes</label><textarea data-i="${i}" data-field="notes">${esc(r.notes)}</textarea><label>Family Rating / Favorite Comments</label><textarea data-i="${i}" data-field="rating">${esc(r.rating)}</textarea><div class="actions"><button onclick="deleteRecipe(${i})" class="danger">Delete Recipe</button></div>`;$("recipeList").appendChild(div)});document.querySelectorAll("#recipeList input,#recipeList textarea,#recipeList select").forEach(el=>{el.oninput=()=>{state.recipes[el.dataset.i][el.dataset.field]=el.value;saveNow();if(el.dataset.field==="title"||el.dataset.field==="category")renderRecipes()};el.onchange=el.oninput})}
window.deleteRecipe=i=>{if(!confirm("Delete this recipe?"))return;state.recipes.splice(i,1);saveNow();renderRecipes()};
function renderList(id,arr){$(id).innerHTML="";arr.forEach((item,i)=>{const li=document.createElement("li");li.className=item.done?"done":"";li.innerHTML=`<input type="checkbox" ${item.done?"checked":""} onchange="toggleItem('${id}',${i})"> ${esc(item.text)} ${item.date?`<span class="small">(${item.date})</span>`:""} <button onclick="removeItem('${id}',${i})" class="danger">x</button>`;$(id).appendChild(li)})}
window.toggleItem=(id,i)=>{const arr=id==="shoppingList"?state.shopping:state.freezer;arr[i].done=!arr[i].done;saveNow();renderAll()};
window.removeItem=(id,i)=>{const arr=id==="shoppingList"?state.shopping:state.freezer;arr.splice(i,1);saveNow();renderAll()};
$("addShoppingBtn").onclick=()=>{if($("shoppingItem").value.trim()){state.shopping.push({text:$("shoppingItem").value.trim(),done:false});$("shoppingItem").value="";saveNow();renderAll()}};
$("addFreezerBtn").onclick=()=>{if($("freezerItem").value.trim()){state.freezer.push({text:$("freezerItem").value.trim(),date:$("freezerDate").value,done:false});$("freezerItem").value="";$("freezerDate").value="";saveNow();renderAll()}};
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="melissas-recipe-binder-backup.json";a.click()};
$("resetBtn").onclick=()=>{if(confirm("Reset the online recipe binder to the starter recipes?")){state=structuredClone(defaultState);dataRef.set(state)}};
function renderAll(){renderRecipes();renderList("shoppingList",state.shopping||[]);renderList("freezerList",state.freezer||[])}
function esc(str){return String(str||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
renderAll();if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
