window.addEventListener("load",()=>{setTimeout(()=>{const s=document.getElementById("splash");if(s)s.classList.add("hide")},2200)});
const firebaseConfig={apiKey:"AIzaSyCSVjnXaDyOQnqNx6HXjwYNqrJu96v8V_U",authDomain:"family-recipes-by-melissa.firebaseapp.com",databaseURL:"https://family-recipes-by-melissa-default-rtdb.firebaseio.com",projectId:"family-recipes-by-melissa",storageBucket:"family-recipes-by-melissa.firebasestorage.app",messagingSenderId:"644873856163",appId:"1:644873856163:web:1b184c62882c7ae0ff8b16",measurementId:"G-CJZ66HXCZN"};
firebase.initializeApp(firebaseConfig);
const db=firebase.database(),dataRef=db.ref("melissasRecipeBinder");
const categories=["Breakfast","Lunch","Dinner","Desserts","Appetizers","Side Dishes","Soups & Stews","Crockpot / Slow Cooker","Instant Pot","Freezer Meals","Holiday Recipes","Family Favorites","Other"];
const featuredRecipes=[
{category:"Desserts",title:"Sugar Cakes",ingredients:"1 cup vegetable shortening (Crisco)\n2 cups sugar\n2 eggs\n1 tsp vanilla\n1 1/2 cups buttermilk\n1 tsp baking soda\n5 cups flour\n1/4 tsp salt\n1 tbsp baking powder\nSugar for dusting the tops",directions:"1. In a large bowl, cream the shortening with the sugar until light and fluffy. Beat in the eggs and vanilla.\n2. In a medium bowl, sift the flour, baking powder, and salt. Add the baking soda to the buttermilk and stir to mix well.\n3. Add the dry ingredients to the sugar and shortening mixture, alternating with the buttermilk. Using a large spatula, mix well to combine.\n4. Drop large spoonfuls onto a greased baking sheet, about 12 to a sheet, and sprinkle the tops with sugar.\n5. Bake at 350°F for about 13 minutes, or until the sugar cakes are slightly brown around the edges.",notes:"Recipe transcribed from the original family recipe image.",rating:"",photo:""},
{category:"Dinner",title:"Creamy Chicken, Broccoli & Gnocchi Skillet",ingredients:"16 oz boneless, skinless chicken breasts or thighs, cut into bite-size pieces\n1 tbsp olive oil\n1 tsp Italian seasoning\n1/2 tsp garlic powder\n1/2 tsp salt\n1/4 tsp black pepper\n3 cloves garlic, minced\n1 cup chicken broth\n1 cup heavy cream or half-and-half\n16 oz potato gnocchi\n9-10 oz broccoli florets, cut into small pieces\n2 1/4 oz grated Parmesan cheese\n1/4 tsp red pepper flakes (optional)",directions:"1. Heat the olive oil in a large skillet over medium-high heat. Season the chicken with Italian seasoning, garlic powder, salt, and black pepper.\n2. Add the chicken and cook for 5-7 minutes, stirring occasionally, until browned and cooked through to 165°F. Transfer the chicken to a plate.\n3. Reduce the heat to medium. Add the minced garlic and cook for about 30 seconds.\n4. Pour in the chicken broth and cream, scraping up any browned bits from the bottom of the skillet.\n5. Stir in the uncooked gnocchi and broccoli. Cover and simmer for 5-7 minutes, stirring once or twice, until the gnocchi are tender and the broccoli is crisp-tender.\n6. Return the chicken to the skillet. Stir in the Parmesan cheese and optional red pepper flakes.\n7. Cook uncovered for 2-3 minutes, stirring gently, until the sauce thickens. Taste and add more salt or pepper as needed.",notes:"Serves 4. Prep time: 10 minutes. Cook time: 25 minutes. For a lighter version, use half-and-half. If the sauce becomes too thick, stir in a splash of chicken broth or milk. Frozen broccoli can be added during the last 4-5 minutes.",rating:"",photo:""},
{category:"Dinner",title:"Easy Kielbasa, Potato & Pepper Skillet",ingredients:"14 oz kielbasa, sliced into 1/2-inch rounds\n1 1/2 lb baby potatoes, halved or quartered\n1 large bell pepper, sliced\n1 medium yellow onion, sliced\n2 tbsp olive oil\n1 tsp garlic powder\n1 tsp smoked paprika\n1/2 tsp salt\n1/4 tsp black pepper\n1/4 cup water\n1 tbsp Dijon mustard (optional, for serving)",directions:"1. Place the potatoes in a microwave-safe bowl with 2 tablespoons of water. Cover loosely and microwave for 5-7 minutes, until they are just beginning to soften. Drain well.\n2. Heat 1 tablespoon of olive oil in a large skillet over medium-high heat. Add the sliced kielbasa and cook for 4-5 minutes, stirring occasionally, until browned. Transfer to a plate.\n3. Add the remaining olive oil to the skillet. Add the potatoes, onion, bell pepper, garlic powder, smoked paprika, salt, and black pepper. Cook for 8-10 minutes, stirring occasionally, until the vegetables are browned and tender.\n4. Add the kielbasa back to the skillet with 1/4 cup water. Stir, cover, and cook for 3-4 minutes until everything is hot and the potatoes are fully tender.\n5. Taste and adjust the seasoning. Serve hot, with Dijon mustard if desired.",notes:"Serves 4. Prep time: 10 minutes. Cook time: 25 minutes. You can add sliced cabbage, green beans, or sauerkraut. For a sweeter version, stir in 1 tablespoon of maple syrup or brown sugar with the water.",rating:"",photo:""},
{category:"Dinner",title:"Cheesy Kielbasa and Rice Skillet",ingredients:"14 oz kielbasa, sliced into rounds\n1 tbsp olive oil\n1 small yellow onion, diced\n2 cloves garlic, minced\n1 cup uncooked long-grain white rice\n2 cups chicken broth\n14.5 oz diced tomatoes, undrained\n1 tsp smoked paprika\n1/4 tsp black pepper\n1 cup frozen peas\n1 1/2 cups shredded cheddar cheese",directions:"1. Heat the olive oil in a large skillet over medium-high heat. Add the kielbasa and cook for 4-5 minutes, stirring occasionally, until browned.\n2. Add the onion and cook for 3 minutes. Stir in the garlic and cook for 30 seconds.\n3. Stir in the rice, chicken broth, diced tomatoes, smoked paprika, and black pepper.\n4. Bring to a gentle boil, then reduce the heat to low. Cover and simmer for 17-20 minutes, until the rice is tender and most of the liquid is absorbed.\n5. Stir in the peas and 1 cup of the cheddar cheese. Cook for 2-3 minutes until the peas are hot and the cheese is melted.\n6. Sprinkle the remaining cheese over the top. Cover for 1-2 minutes, until melted, then serve.",notes:"Serves 4. Prep time: 10 minutes. Cook time: 25 minutes. Use instant rice only if you reduce the broth and follow the rice package timing. Broccoli or corn can replace the peas.",rating:"",photo:""}
];
const starterRecipes=[...featuredRecipes,{category:"Breakfast",title:"Hash Brown Crust Breakfast Casserole",ingredients:"30 oz thawed hash browns\n3 tbsp melted butter\n1 lb breakfast sausage\n8 oz mushrooms, sliced\n2 cups spinach\n10 eggs\n1 cup milk\n2 cups shredded cheddar cheese\nSalt, pepper, garlic powder, onion powder",directions:"Press hash browns with butter into a greased 9x13 pan. Bake at 425°F for 20-25 minutes. Cook sausage, mushrooms, and spinach. Layer over crust. Whisk eggs, milk, and seasonings. Pour over filling. Top with cheese. Bake at 375°F for 30-35 minutes.",notes:"Freezes well. Cool completely before freezing.",rating:"",photo:""},{category:"Breakfast",title:"Cinnamon Roll Casserole",ingredients:"2 cans cinnamon rolls\n4 eggs\n1/2 cup milk or cream\n1 tsp vanilla\n1 tsp cinnamon",directions:"Cut cinnamon rolls into pieces. Place in greased baking dish. Whisk eggs, milk, vanilla, and cinnamon. Pour over rolls. Bake at 350°F for 25-30 minutes. Add icing after baking.",notes:"Best frozen after baking.",rating:"",photo:""}];
const defaultState={recipes:starterRecipes,mealPlan:"",freezer:[],shopping:[],christmas:"Breakfast casserole\nDinner menu\nDesserts\nShopping list",easter:"Brunch menu\nDinner menu\nDesserts",mothersDay:"Brunch ideas\nFamily favorites",thanksgiving:"Turkey day sides\nBreakfast for the weekend\nDesserts",gatherings:"Birthdays, cookouts, family dinners, and potlucks",familyNotes:""};
const $=id=>document.getElementById(id);let state=structuredClone(defaultState),loaded=false,saveTimer=null;
function saveNow(){if(!loaded)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{dataRef.set(state);$("status").textContent="Saved online"},400)}
function setupCats(){let opts='<option value="All">All Recipes</option>'+categories.map(c=>`<option>${c}</option>`).join("");$("categoryFilter").innerHTML=opts;$("importCategory").innerHTML=categories.map(c=>`<option ${c==="Dinner"?"selected":""}>${c}</option>`).join("");$("scanCategory").innerHTML=categories.map(c=>`<option ${c==="Family Favorites"?"selected":""}>${c}</option>`).join("")}setupCats();
dataRef.on("value",snap=>{const data=snap.val();state=data?{...structuredClone(defaultState),...data}:structuredClone(defaultState);state.recipes=Array.isArray(state.recipes)?state.recipes:[];const existingTitles=new Set(state.recipes.map(r=>(r.title||"").trim().toLowerCase()));const missingFeaturedRecipes=featuredRecipes.filter(r=>!existingTitles.has(r.title.toLowerCase()));if(missingFeaturedRecipes.length)state.recipes.unshift(...missingFeaturedRecipes.map(r=>structuredClone(r)));if(!data||missingFeaturedRecipes.length)dataRef.set(state);loaded=true;syncInputs();renderAll();$("status").textContent="Saved online with Firebase"},err=>{$("status").textContent="Firebase connection error";console.error(err)});
document.querySelectorAll("nav button").forEach(btn=>{btn.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active");$(btn.dataset.tab).classList.add("active")}});
function syncInputs(){["mealPlan","christmas","easter","mothersDay","thanksgiving","gatherings","familyNotes"].forEach(id=>{if(document.activeElement!==$(id))$(id).value=state[id]||""})}
["mealPlan","christmas","easter","mothersDay","thanksgiving","gatherings","familyNotes"].forEach(id=>{$(id).oninput=()=>{state[id]=$(id).value;saveNow()}});
$("categoryFilter").onchange=renderRecipes;$("searchBox").oninput=renderRecipes;
$("openImportBtn").onclick=()=>$("importPanel").classList.remove("hidden");$("closeImportBtn").onclick=()=>$("importPanel").classList.add("hidden");$("openScanBtn").onclick=()=>$("scanPanel").classList.remove("hidden");$("closeScanBtn").onclick=()=>$("scanPanel").classList.add("hidden");
$("addRecipeBtn").onclick=()=>{state.recipes.unshift({category:"Dinner",title:"New Recipe",ingredients:"",directions:"",notes:"",rating:"",photo:""});saveNow();renderRecipes()};
$("importRecipeBtn").onclick=()=>{const text=$("importText").value.trim();if(!text)return alert("Paste a recipe first.");const p=parseRecipe(text);state.recipes.unshift({category:$("importCategory").value||"Other",title:p.title||"Imported Recipe",ingredients:p.ingredients,directions:p.directions,notes:p.notes,rating:"",photo:""});$("importText").value="";$("importPanel").classList.add("hidden");saveNow();renderRecipes()};
$("saveScanBtn").onclick=()=>{const file=$("scanPhoto").files[0];const rec={category:$("scanCategory").value||"Family Favorites",title:$("scanTitle").value.trim()||"Scanned Recipe",ingredients:"",directions:"",notes:$("scanNotes").value||"Recipe photo saved. Add ingredients and directions later.",rating:"",photo:""};if(!file){state.recipes.unshift(rec);clearScan();saveNow();renderRecipes();return}resizeImage(file,900,url=>{rec.photo=url;state.recipes.unshift(rec);clearScan();saveNow();renderRecipes()})};
function clearScan(){$("scanTitle").value="";$("scanPhoto").value="";$("scanNotes").value="";$("scanPanel").classList.add("hidden")}
function parseRecipe(text){const lines=text.split(/\r?\n/).map(l=>l.trim()).filter(Boolean),title=lines[0]||"Imported Recipe",low=lines.map(l=>l.toLowerCase());let i=low.findIndex(l=>l.includes("ingredients")),d=low.findIndex(l=>l.includes("directions")||l.includes("instructions")||l.includes("method"));if(i>=0&&d>i)return{title,ingredients:lines.slice(i+1,d).join("\n"),directions:lines.slice(d+1).join("\n"),notes:""};return{title,ingredients:"",directions:"",notes:lines.slice(1).join("\n")}}
function resizeImage(file,maxWidth,cb){const reader=new FileReader();reader.onload=e=>{const img=new Image();img.onload=()=>{const scale=Math.min(maxWidth/img.width,1),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);cb(c.toDataURL("image/jpeg",.72))};img.src=e.target.result};reader.readAsDataURL(file)}
function categoryOptions(sel){return categories.map(c=>`<option ${c===sel?"selected":""}>${c}</option>`).join("")}
function renderRecipes(){$("recipeList").innerHTML="";const filter=$("categoryFilter").value||"All",search=($("searchBox").value||"").toLowerCase().trim();state.recipes.forEach((r,i)=>{const hay=`${r.title} ${r.category} ${r.ingredients} ${r.directions} ${r.notes} ${r.rating}`.toLowerCase();if(filter!=="All"&&r.category!==filter)return;if(search&&!hay.includes(search))return;const div=document.createElement("div");div.className="card";div.innerHTML=`<div class="card-title"><h3>${esc(r.title||"Untitled Recipe")}</h3><span class="badge">${esc(r.category||"Other")}</span></div>${r.photo?`<img src="${r.photo}" class="recipe-photo">`:""}<label>Category</label><select data-i="${i}" data-field="category">${categoryOptions(r.category||"Other")}</select><label>Recipe Name</label><input value="${esc(r.title)}" data-i="${i}" data-field="title"><label>Ingredients</label><textarea data-i="${i}" data-field="ingredients">${esc(r.ingredients)}</textarea><label>Directions</label><textarea data-i="${i}" data-field="directions">${esc(r.directions)}</textarea><label>Notes / Freezer Instructions / Changes</label><textarea data-i="${i}" data-field="notes">${esc(r.notes)}</textarea><label>Family Rating / Favorite Comments</label><textarea data-i="${i}" data-field="rating">${esc(r.rating)}</textarea><div class="actions"><button onclick="deleteRecipe(${i})" class="danger">Delete Recipe</button></div>`;$("recipeList").appendChild(div)});document.querySelectorAll("#recipeList input,#recipeList textarea,#recipeList select").forEach(el=>{el.oninput=()=>{state.recipes[el.dataset.i][el.dataset.field]=el.value;saveNow();if(el.dataset.field==="title"||el.dataset.field==="category")renderRecipes()};el.onchange=el.oninput})}
window.deleteRecipe=i=>{if(!confirm("Delete this recipe?"))return;state.recipes.splice(i,1);saveNow();renderRecipes()};
function renderList(id,arr){$(id).innerHTML="";arr.forEach((item,i)=>{const li=document.createElement("li");li.className=item.done?"done":"";li.innerHTML=`<input type="checkbox" ${item.done?"checked":""} onchange="toggleItem('${id}',${i})"> ${esc(item.text)} ${item.date?`<span class="small">(${item.date})</span>`:""} <button onclick="removeItem('${id}',${i})" class="danger">x</button>`;$(id).appendChild(li)})}
window.toggleItem=(id,i)=>{const arr=id==="shoppingList"?state.shopping:state.freezer;arr[i].done=!arr[i].done;saveNow();renderAll()};
window.removeItem=(id,i)=>{const arr=id==="shoppingList"?state.shopping:state.freezer;arr.splice(i,1);saveNow();renderAll()};
$("addShoppingBtn").onclick=()=>{if($("shoppingItem").value.trim()){state.shopping.push({text:$("shoppingItem").value.trim(),done:false});$("shoppingItem").value="";saveNow();renderAll()}};
$("addFreezerBtn").onclick=()=>{if($("freezerItem").value.trim()){state.freezer.push({text:$("freezerItem").value.trim(),date:$("freezerDate").value,done:false});$("freezerItem").value="";$("freezerDate").value="";saveNow();renderAll()}};
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="melissas-recipe-binder-backup.json";a.click()};
$("resetBtn").onclick=()=>{if(confirm("Reset the online recipe binder to the starter recipes?")){state=structuredClone(defaultState);dataRef.set(state)}};
function renderAll(){renderRecipes();renderList("shoppingList",state.shopping||[]);renderList("freezerList",state.freezer||[])}
function esc(str){return String(str||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
renderAll();if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");